# This is a basic workflow to help you get started with Actions

name: Build List

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
            Thank you for submitting your project.
            Please make sure you fill out https://yleojkzxfvm.typeform.com/avaxproject so we have your contact information. 