# This is a basic workflow to help you get started with Actions

name: Build List and Comment

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run a multi-line script
        run: node actions/createList.js
      - name: commit new file
        uses: EndBug/add-and-commit@v7
        with: 
          author_name: CI bot
          push: true
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            Thank you for submitting your project.
            Please make sure you fill out https://yleojkzxfvm.typeform.com/avaxproject so we have your contact information. 